Z /etc/greetd 0644 - - - -
L /var/lib/greetd/.config/systemd/user/xdg-desktop-portal.service - - - - /dev/null
d /var/lib/AccountsService 0775 root root - -
d /var/lib/AccountsService/icons 0775 root root - -
d /var/lib/AccountsService/users 0700 root root - -
d /var/lib/blueman 0755 root root - -
