d /var/lib/greetd 0755 root root -
d /var/lib/greetd/.config 0755 root root -
d /var/lib/greetd/.config/systemd 0755 root root -
d /var/lib/greetd/.config/systemd/user 0755 root root -

L /var/lib/greetd/.config/systemd/user/xdg-desktop-portal.service - - - - /dev/null
